---
- hosts: localhost
  become: true
  vars:
    - dotfiles_repo: git@github.com:mich-murphy/dotfiles.git
    - source_key: "./.ssh/id_rsa"
    - dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
  - name: System update
    tags: always
    pacman:
      update_cache: yes
      upgrade: yes

  tasks:
  - include_tasks: tasks/setup.yml
