- hosts: localhost
  vars:
    - dotfiles_repo: git@github.com:mich-murphy/dotfiles.git
  pre_tasks:
  - name: System update
    become: true
    community.general.pacman:
      update_cache: yes
      upgrade: yes
    tags:
      - zsh
      - python

  tasks:
  - include_tasks: tasks/zsh.yml
  - include_tasks: tasks/python.yml
