---
- name: create mm user
  user:
    name: mm
    groups: wheel

- name: add sudoers file for mm
  copy: 
    src: sudoer_mm
    dest: /etc/sudoers.d/mm
    owner: root
    group: wheel
    mode: 0440

- name: Install core system packages
  package:
    name:
      - man
      - man-pages
      - tldr
      - xorg
      - openssh
      - networkmanager
      - xsel
      - fzf
      - scrot
      - udiskie
      - lxappearance
      - xcape
      - ripgrep
      - tmux
      - tmuxp
      - dunst
      - libnotify
      - diff-so-fancy
      - i3-gaps
      - i3lock
      - polybar
      - rofi
      - feh
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      - neovim
      - python-neovim
      - python2-neovim
      - ruby-neovim
      - nodejs-neovim
      - yarn
      - kitty
      - firefox
    state:
      - latest
  tags:
    - setup
