---
- name: install sudo
  package:
    name: sudo
    state: latest

- name: create mm user
  user:
    name: mm
    password: "{{ password | password_hash('sha512') }}"
    groups: wheel
    update_password: on_create

- lineinfile:
   path: /etc/sudoers
   state: present
   regexp: '^%wheel\s'
   line: '%wheel ALL=(ALL) ALL'

- name: install core system packages
  package:
    name:
      - man
      - man-pages
      - tldr
      - xorg
      - openssh
      - networkmanager
      - xsel
      - udiskie
      - lxappearance
      - xcape
    state: latest
  tags:
    - setup
