---
- vars_prompt:
    name: "user_password"    
    prompt: "Enter a password for the user"    
    private: yes    
    encrypt: "md5_crypt" #need to have python-passlib installed in local machine
    confirm: yes    
    salt_size: 7

- name: install sudo
  package:
    name: sudo
    state: latest

- name: create mm user
  user:
    name: mm
    password: "{{ user_password }}"
    groups: wheel

- lineinfile:
   path: /etc/sudoers
   state: present
   regexp: '^%wheel\s'
   line: '%wheel ALL=(ALL) ALL'

- name: install core system packages
  package:
    name:
      - man
      - man-pages
      - tldr
      - xorg
      - openssh
      - networkmanager
      - xsel
      - udiskie
      - lxappearance
      - xcape
    state: latest
  tags:
    - setup
