---
- name: install sudo
  package:
    name: sudo
    state: latest

- name: create mm user
  user:
    name: mm
    password: "{{ user_password }}"
    groups: wheel

- lineinfile:
   path: /etc/sudoers
   state: present
   regexp: '^%wheel\s'
   line: '%wheel ALL=(ALL) ALL'

- name: install core system packages
  package:
    name:
      - man
      - man-pages
      - tldr
      - xorg
      - openssh
      - networkmanager
      - xsel
      - fzf
      - scrot
      - udiskie
      - lxappearance
      - xcape
      - ripgrep
      - tmux
      - tmuxp
      - dunst
      - libnotify
      - diff-so-fancy
      - i3-gaps
      - i3lock
      - rofi
      - feh
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      - neovim
      - python-neovim
      - python2-neovim
      - ruby-neovim
      - nodejs-neovim
      - yarn
      - kitty
      - firefox
    state: latest
  tags:
    - setup
