- name: Install zsh
  become: true
  community.general.pacman: 
    name: zsh
    state: latest
  tags: 
    - core
    - zsh
- name: Change shell
  shell: chsh -s $(which zsh)
  tags: 
    - core
    - zsh
